# Generated by Django 4.2 on 2024-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPlatform', '0005_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, upload_to='choices/'),
        ),
    ]
