# Generated by Django 4.2 on 2024-10-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyPlatform', '0007_usertests_usertestanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertests',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
